name: Release

on:
  push:
    tags:
      - "v*"

env:
  PROJECT_NAME: ai_commit_cli

permissions:
  contents: write
  discussions: write
  pull-requests: write

jobs:
  build-release:
    name: Build Release (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              target: x86_64-unknown-linux-gnu,
              os: ubuntu-latest,
              extension: "",
            }
          - { target: x86_64-apple-darwin, os: macos-latest, extension: "" }
          - { target: aarch64-apple-darwin, os: macos-latest, extension: "" }

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}

      - name: Install dependencies (Ubuntu)
        if: matrix.job.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev

      - name: Install dependencies (macOS)
        if: matrix.job.os == 'macos-latest'
        run: |
          brew install openssl@3

      - name: Build target
        run: |
          cargo build --release --target ${{ matrix.job.target }}

      - name: Rename artifacts
        shell: bash
        run: |
          mv target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }}{,-${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }}-${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}
