name: Release

on:
  push:
    tags:
      - "v*"

env:
  PROJECT_NAME: aic

permissions:
  contents: write
  discussions: write
  pull-requests: write

jobs:
  build-release:
    name: Build Release (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              target: x86_64-unknown-linux-gnu,
              os: ubuntu-latest,
              extension: "",
            }
          - { target: x86_64-apple-darwin, os: macos-latest, extension: "" }
          - { target: aarch64-apple-darwin, os: macos-latest, extension: "" }

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}

      - name: Install dependencies (Ubuntu)
        if: matrix.job.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev

      - name: Install dependencies (macOS)
        if: matrix.job.os == 'macos-latest'
        run: |
          brew install openssl@3

      - name: Build target
        run: |
          # Show Rust and cargo information
          rustc --version
          cargo --version
          rustup show

          # Show current directory structure
          echo "Current directory structure:"
          ls -la

          # Build with verbose output
          cargo build --release --target ${{ matrix.job.target }} -vv

          # Show target directory structure after build
          echo "Target directory structure after build:"
          ls -R target/

      - name: Check binary
        shell: bash
        run: |
          echo "Checking binary location..."
          ls -la target/${{ matrix.job.target }}/release/
          echo "Binary details:"
          file target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }} || true

      - name: Rename artifacts
        shell: bash
        run: |
          SOURCE="target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }}"
          DEST="target/${{ matrix.job.target }}/release/ai_commit_cli-${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}"

          if [ -f "$SOURCE" ]; then
            echo "Found binary at $SOURCE"
            mv "$SOURCE" "$DEST"
          else
            echo "Error: Binary not found at $SOURCE"
            echo "Contents of release directory:"
            ls -la target/${{ matrix.job.target }}/release/
            exit 1
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.job.target }}/release/ai_commit_cli-${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}
